### ISSUE TITLE
failed to build on RHEL 5.x

### ISSUE THREAD

**Issue by yankaiqian** [huzheng001/stardictd#1]
Tried stardictd-0.4.1, works well on RHEL 6.x and 7.x, but failed to build on RHEL 5.x, I know that RHEL 5.x is old release and should be deprecated now, but is it possible that stardictd could run on RHEL 5.x too?

```
$ make
make  all-recursive
make[1]: Entering directory `/home/tsg/stardict/stardictd-0.4.1'
Making all in doc
make[2]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/doc'
Making all in etc
make[2]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/etc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/etc'
Making all in src
make[2]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/src'
Making all in lib
make[3]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/src/lib'
g++ -DHAVE_CONFIG_H -I. -I../..  -Wall -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include     -g -O2 -MT lib.o -MD -MP -MF .deps/lib.Tpo -c -o lib.o lib.cpp
stddict.hpp:188: error: ‘GRegex’ has not been declared
stddict.hpp:189: error: ‘GRegex’ has not been declared
make[3]: *** [lib.o] Error 1
make[3]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/src/lib'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1'
make: *** [all] Error 2
```

**Comment by huzheng001** [comment]
‘GRegex’ has not been declared.

You need to update libglib2.0-dev !

**Comment by huzheng001** [comment]
You need to update glib2!

2016-03-24 11:36 GMT+08:00 yankaiqian <notifications@github.com>:

> Tried stardictd-0.4.1, works well on RHEL 6.x and 7.x, but failed to build
> on RHEL 5.x, I know that RHEL 5.x is old release and should be deprecated
> now, but is it possible that stardictd could run on RHEL 5.x too?
>
> $ make
> make  all-recursive
> make[1]: Entering directory `/home/tsg/stardict/stardictd-0.4.1'
> Making all in doc
> make[2]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/doc'
> make[2]: Nothing to be done for `all'.
> make[2]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/doc'
> Making all in etc
> make[2]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/etc'
> make[2]: Nothing to be done for `all'.
> make[2]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/etc'
> Making all in src
> make[2]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/src'
> Making all in lib
> make[3]: Entering directory `/home/tsg/stardict/stardictd-0.4.1/src/lib'
> g++ -DHAVE_CONFIG_H -I. -I../..  -Wall -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include     -g -O2 -MT lib.o -MD -MP -MF .deps/lib.Tpo -c -o lib.o lib.cpp
> stddict.hpp:188: error: ‘GRegex’ has not been declared
> stddict.hpp:189: error: ‘GRegex’ has not been declared
> make[3]: *** [lib.o] Error 1
> make[3]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/src/lib'
> make[2]: *** [all-recursive] Error 1
> make[2]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1/src'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/home/tsg/stardict/stardictd-0.4.1'
> make: *** [all] Error 2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/huzheng001/stardictd/issues/1>
>



-- 
http://www.huzheng.org
